# Uncomment the next line to define a global platform for your project
platform :ios, '7.0'

target 'SCJSONUtilDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SCJSONUtil',:path => '../'

end

target 'SCJSONUtilTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SCJSONUtil',:path => '../'

end